"""add iqamah

Revision ID: 6ac425782768
Revises: 5e66b6616765
Create Date: 2026-02-25 11:37:54.764418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac425782768'
down_revision = '5e66b6616765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iqamah_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fajr', sa.String(length=10), nullable=False),
    sa.Column('dhuhr', sa.String(length=10), nullable=False),
    sa.Column('asr', sa.String(length=10), nullable=False),
    sa.Column('maghrib', sa.String(length=10), nullable=False),
    sa.Column('isha', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iqamah_times')
    # ### end Alembic commands ###
